version: "3.9"
services:
  database:
    container_name: afina_e2e_database
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./db/e2e/data:/data/db"
  backend:
    build:
      context: "./apps/backend"
    container_name: afina_e2e_backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - AFINA_DB_URL=mongodb://database:27017/afina
  promo:
    build:
      context: ./apps/promo
    container_name: afina_e2e_promo
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - AFINA_BACKEND_URL=http://backend:3001
  e2e:
    build:
      context: ./apps/e2e
    container_name: afina_e2e_e2e
    depends_on:
      - promo
    ports:
      - "3002:3002"
    environment:
      - AFINA_PROMO_URL=http://promo:3000
      - AFINA_BACKEND_URL=http://backend:3001
