version: "3.9"
services:
  database:
    container_name: afina_prod_database
    image: mongo
    restart: always
    volumes:
      - "./db/prod/data:/data/db"
  backend:
    build:
      context: "./apps/backend"
    container_name: afina_prod_backend
    depends_on:
      - database
    environment:
      - AFINA_DB_URL=mongodb://database:27017/afina
  promo:
    build:
      context: ./apps/promo
    container_name: afina_prod_promo
    depends_on:
      - backend
    environment:
      - AFINA_BACKEND_URL=http://backend:3001
  nginx:
    container_name: afina_prod_nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - promo
