version: "3.9"
services:
  database:
    container_name: afina_e2e_database
    image: mongo
    restart: always
    volumes:
      - "./db/e2e/data:/data/db"
  backend:
    build:
      context: "./apps/backend"
    container_name: afina_e2e_backend
    depends_on:
      - database
    environment:
      - AFINA_DB_URL=mongodb://database:27017/afina
  promo:
    build:
      context: ./apps/promo/
      dockerfile: Dockerfile.e2e
    container_name: afina_e2e_promo
    depends_on:
      - backend
  e2e:
    build:
      context: ./apps/e2e
    container_name: afina_e2e_e2e
    depends_on:
      - promo
    environment:
      - AFINA_PROMO_URL=http://promo:3000
      - AFINA_BACKEND_URL=http://backend:3001
